apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: blissfish-deployment
spec:
  selector:
    matchLabels:
      app: blissfish-app
  replicas: 1 # tells deployment to run 2 pod matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: blissfish-app
    spec:
      containers:
      - name: service1
        image: gcr.io/blissfish-191215/service1:0.0.1
        ports:
        - containerPort: 8080
      - name: service2
        image: gcr.io/blissfish-191215/service2:0.0.1
        ports:
        - containerPort: 8080
      - name: echo
        image: gcr.io/blissfish-191215/echo:0.0.1
        ports:
        - containerPort: 8080